apiVersion: v1
kind: Service
metadata:
  name: inventory-reservation
spec:
  selector:
    app: inventory-reservation
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8064