apiVersion: v1
kind: Service
metadata:
  name: fulfillment-service
spec:
  selector:
    app: fulfillment-service
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8063