apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription-service
  labels:
    app: prescription-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prescription-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prescription-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: nvsr07/prescription-service
        imagePullPolicy: Always
        name: prescription-service
        ports:
        - containerPort: 8067
          protocol: TCP

