apiVersion: v1
kind: Service
metadata:
  name: prescription-service
spec:
  selector:
    app: prescription-service
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8067