apiVersion: v1
kind: Service
metadata:
  name: financial-transaction
spec:
  selector:
    app: financial-transaction
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8062